version: '3.9'

services:
  bot:
    build:
      context: ..
      dockerfile: Dockerfile

    container_name: "chats-bot"

    volumes:
      - ../app/:/app/
      - ../photos/:/app/photos/

    env_file:
      - ../.env

    command: "python main.py"
    networks:
      - backend

networks:
  backend:
    driver: bridge
